shell = "bash -c '{}'"
default-scheme = "base24-rose-punk"

hooks = [
    "echo \"The current scheme is: $(tinty current)\"",
    ]

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = "source \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-terminal"
path = "https://github.com/tinted-theming/tinted-terminal"
themes-dir = "themes/kitty"
hook = "kitten @ load-config"
supported-systems = ["base16", "base24"]

[[items]]
name = "base24-waybar"
path = "git@github.com:tijptjik/base24-waybar.git"
themes-dir = "colors"
hook = "killall waybar; waybar"
supported-systems =  ["base16", "base24"]

[[items]]
name = "base24-dunst"
path = "https://github.com/tijptjik/base24-dunst"
themes-dir = "themes"
hook = "dunstctl reload"
supported-systems =  ["base16", "base24"]
